### ISSUE TITLE
"NoCollisionSpec"

### ISSUE THREAD

**Issue by wadoon** [VerifAPS/stvs#8]
After loading "minmax.xml" specification, "NoCollisionSpec" is in the tab title. 

![grafik](https://cloud.githubusercontent.com/assets/104259/24430451/fbf25d6e-1416-11e7-97cf-021b15f59724.png)

There should be the filename.

**Comment by limond** [comment]
This is most likely expected behaviour since the title is taken from the 'title' attribute (if specified) of the root node of a specification file. The title of a specification does not have to be its filename. The name of a specification can be changed by opening the context menu of a tab and choosing the 'Rename' option.

**Comment by wadoon** [comment]
If no name are present, the filename should be taken.
